### PR TITLE
Fix unchecked access

### LINKED ISSUE #457: [NCC-E008263-4VP] Unchecked Accesses to Data Structures
In multiple instances, dictionary are accessed directly, which leads to panics if the key is not present. See report for more details.

Also, in `aggregate()`, we should make sure that the 3 arguments have matching sets of identifiers.

Fix those:

- It's probably better to avoid indexing directly altogether and use `.get()` instead, handling the error. Try enabling the [`indexing_slicing` lint ](https://rust-lang.github.io/rust-clippy/master/index.html#/indexing_slicing) (possibly with an exception in test code)
- Add a validation in `aggregate()` to make sue the identifier sets are consistent (`signing_package.signing_commitments` and `signature_shares` should have equal keys, and they should be a subset of `pubkeys.signer_pubkeys`)

### PR DESCRIPTION
**Pull request by conradoplg**
Closes #457 

Adds two lints to forbid slicing and unwrapping (with exception to test code), and changes all instances of those to respectively using `.get()` and handling `None`, and handling the error or using `.expect()`

### CODE REVIEW

File: frost-core/src/frost.rs [hunk 1]
```diff
@@ -267,9 +255,12 @@ where
...
 
-    /// Get a signing commitment by its participant identifier.
-    pub fn signing_commitment(&self, identifier: &Identifier<C>) -> round1::SigningCommitments<C> {
-        self.signing_commitments[identifier]
+    /// Get a signing commitment by its participant identifier, or None if not found.
+    pub fn signing_commitment(
+        &self,
+        identifier: &Identifier<C>,
+    ) -> Option<round1::SigningCommitments<C>> {
+        self.signing_commitments.get(identifier).copied()
```
Comment (dconnolly) [inline frost-core/src/frost.rs:263]: 👍

File: frost-core/src/frost.rs [hunk 2]
```diff
@@ -362,7 +353,9 @@ where
             return Err(Error::IdentityCommitment);
         }
 
-        let binding_factor = binding_factor_list[*commitment_identifier].clone();
+        let binding_factor = binding_factor_list
+            .get(commitment_identifier)
+            .ok_or(Error::UnknownIdentifier)?;
```
Comment (dconnolly) [inline frost-core/src/frost.rs:358]: 👍

File: frost-core/src/frost.rs [hunk 3]
```diff
@@ -410,6 +403,19 @@ pub fn aggregate<C>(
...
 {
+    // Check if signing_package.signing_commitments and signature_shares have
+    // the same set of identifiers, and if they are all in pubkeys.signer_pubkeys.
+    if signing_package.signing_commitments().len() != signature_shares.len() {
+        return Err(Error::UnknownIdentifier);
+    }
+    if !signing_package
+        .signing_commitments()
+        .keys()
+        .all(|id| signature_shares.contains_key(id) && pubkeys.signer_pubkeys().contains_key(id))
```
Comment (dconnolly) [inline frost-core/src/frost.rs:414]: nice

File: frost-core/src/frost.rs [hunk 4]
```diff
@@ -458,17 +464,20 @@ where
             let signer_pubkey = pubkeys
                 .signer_pubkeys
                 .get(signature_share_identifier)
-                .unwrap();
+                .ok_or(Error::UnknownIdentifier)?;
```
Comment (dconnolly) [inline frost-core/src/frost.rs:467]: 👍

File: frost-core/src/frost.rs [hunk 5]
```diff
@@ -458,17 +464,20 @@ where
...
 
             // Compute Lagrange coefficient.
             let lambda_i = derive_interpolating_value(signature_share_identifier, signing_package)?;
 
-            let binding_factor = binding_factor_list[*signature_share_identifier].clone();
+            let binding_factor = binding_factor_list
+                .get(signature_share_identifier)
+                .ok_or(Error::UnknownIdentifier)?;
```
Comment (dconnolly) [inline frost-core/src/frost.rs:474]: 👍

File: frost-core/src/frost.rs [hunk 6]
```diff
@@ -458,17 +464,20 @@ where
...
 
             // Compute the commitment share.
             let R_share = signing_package
                 .signing_commitment(signature_share_identifier)
-                .to_group_commitment_share(&binding_factor);
+                .ok_or(Error::UnknownIdentifier)?
```
Comment (dconnolly) [inline frost-core/src/frost.rs:479]: 👍

File: frost-core/src/frost/keys.rs [hunk 7]
```diff
@@ -328,6 +328,12 @@ where
 
         Ok(Self(coefficient_commitments))
     }
+
+    /// Get the first commitment (which is equivalent to the VerifyingKey),
+    /// or an error if the vector is empty.
+    pub(crate) fn first(&self) -> Result<CoefficientCommitment<C>, Error<C>> {
+        self.0.get(0).ok_or(Error::MissingCommitment).copied()
+    }
```
Comment (dconnolly) [inline frost-core/src/frost/keys.rs:336]: 👍

File: frost-core/src/frost/keys.rs [hunk 8]
```diff
@@ -518,7 +524,10 @@ fn evaluate_polynomial<C: Ciphersuite>(
         value = value + *coeff;
         value *= ell_scalar;
     }
-    value = value + coefficients[0];
+    value = value
+        + *coefficients
+            .get(0)
+            .expect("coefficients must have at least one element");
```
Comment (dconnolly) [inline frost-core/src/frost/keys.rs:530]: 👍

File: frost-core/src/frost/keys/dkg.rs [hunk 9]
```diff
@@ -130,8 +130,8 @@ pub mod round1 {
         C: Ciphersuite,
     {
         fn zeroize(&mut self) {
-            for i in 0..self.coefficients.len() {
-                self.coefficients[i] = <<C::Group as Group>::Field>::zero();
+            for c in self.coefficients.iter_mut() {
+                *c = <<C::Group as Group>::Field>::zero();
```
Comment (dconnolly) [inline frost-core/src/frost/keys/dkg.rs:134]: 👍

File: frost-core/src/scalar_mul.rs [hunk 10]
```diff
@@ -1,5 +1,9 @@
 //! Non-adjacent form (NAF) implementations for fast batch scalar multiplcation
 
+// We expect slicings in this module to never panic due to algorithmic
+// constraints.
+#![allow(clippy::indexing_slicing)]
```
Comment (dconnolly) [inline frost-core/src/scalar_mul.rs:5]: 👍

File: frost-core/src/tests/ciphersuite_generic.rs [hunk 11]
```diff
@@ -196,6 +213,26 @@ fn check_aggregate_error<C: Ciphersuite + PartialEq>(
...
+    // Insert a new share (copied from other existing share) with an invalid identifier
+    signature_shares.insert(
+        invalid_identifier,
+        *signature_shares.values().next().unwrap(),
+    );
+    // Should error, but not panic
+    frost::aggregate(&signing_package, &signature_shares, &pubkey_package)
+        .expect_err("should not work");
+}
+
```
Comment (dconnolly) [inline frost-core/src/tests/ciphersuite_generic.rs:235]: 👍

**Review by dconnolly — APPROVED** [review]
lgtm! 🎉
